import { OrderStatus } from '../enums/order-status.enum';

export interface LaborItem {
  description: string;
  technicianName: string;
  hours: number;
  ratePerHour: number;
  /** hours × ratePerHour — stored denormalized for fast display */
  total: number;
}

export interface PartUsed {
  /** Reference to InventoryItem document */
  inventoryItemId: string;
  sku: string;
  name: string;
  quantity: number;
  unitPrice: number;
  /** quantity × unitPrice — stored denormalized */
  total: number;
}

export interface WorkOrder {
  id: string;
  /** Reference to Client document */
  clientId: string;
  /** Reference to Motorcycle document */
  motorcycleId: string;
  status: OrderStatus;
  title: string;
  description: string;
  partsUsed: PartUsed[];
  laborItems: LaborItem[];
  subtotalParts: number;
  subtotalLabor: number;
  /** Decimal fraction, e.g. 0.20 for 20% VAT */
  taxRate: number;
  totalCost: number;
  /** HTML receipt generated by the AI assistant */
  aiGeneratedReceiptHtml?: string;
  /** The original prompt passed to the AI — kept for audit */
  aiPromptUsed?: string;
  assignedTechnicianId?: string;
  scheduledDate?: Date;
  completedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

/** Payload type for creating a new order (no server-generated fields) */
export type CreateWorkOrderPayload = Omit<WorkOrder, 'id' | 'createdAt' | 'updatedAt'>;
/** Payload type for AI draft (subset used to pre-fill the form) */
export type WorkOrderFormPatch = Pick<WorkOrder, 'title' | 'description' | 'partsUsed' | 'laborItems'>;
